image: node

stages:
  - build
  - package
  - deploy
    
before_script:
  - whoami
  - ls
  
  
include:
  - template: SAST.gitlab-ci.yml
variables:
  SAST_GOSEC_LEVEL: 2
    
test site:
  stage: test
  before_script:
    - npm install -g broken-link-checker@0.7.8 wait-on@3.3.0
  script:
    - cd website
    - npm install && npm run start &
    - wait-on http://localhost:3000/ -t 300000
    - blc  --recursive --exclude-external http://localhost:3000
  tags:
    - lab

package site:
  stage: package
  cache:
    key: site-package
    policy: push
    paths:
      - /website/build
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    expire_in: 30 mins
    paths:
      - ./website/build/missaodevops     
  script:
    - cd website
    - npm install
    - npm run build
  tags:
    - lab
    
# vulnerabilidade check:
#   stage: test
#   script:
#     - cd website && npm install && npm run scan
#   tags:
#     - lab

vulnerabilidade check:
    stage: test
    before_script:
        - npm install && npm install -g snyk
    script:
        -  cd website
        -  snyk monitor

deploy to staging:
  stage: deploy
  variables:
    CNAME: staging.renatovieiradesouzabrasil.surge.sh
  cache:
    key: site-package
    policy: pull
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/missaodevops --domain ${CNAME}
  after_script:
    - whoami
  environment:
    name: staging
    url: http://${CNAME}
  only:
    - develop    
  tags:
    - lab
    
deploy to release:
  stage: deploy
  variables:
    CNAME: $CI_COMMIT_REF_SLUG.renatovieiradesouza1.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
  before_script:
    - npm install -g surge@^0.20.1
  script: 
    - surge --project ./website/build/missaodevops --domain ${CNAME}
    - echo ${CNAME}
  after_script:
    - whoami
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}
    on_stop: stop_release
  only:
    - release
  tags:
    - lab

stop_release:
  stage: deploy
  variables:
    CNAME: $CI_COMMIT_REF_SLUG.renatovieiradesouza1.surge.sh
    GIT_STRATEGY: none
  before_script:
    - npm install -g surge@^0.20.1
  script: 
    - surge teardown ${CNAME}
  after_script:
    - whoami
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://${CNAME}
    action: stop
  only:
    - release
  tags:
    - lab
    
deploy to production:
  stage: deploy
  variables:
    CNAME: renatovieiradesouzabrasil.surge.sh
    GIT_STRATEGY: none
  cache:
    key: site-package
    policy: pull
  before_script:
    - npm install -g surge
  script:
    - surge --project ./website/build/missaodevops --domain ${CNAME}
  after_script:
    - whoami
  environment:
    name: production
    url: http://${CNAME}
  only:
    - master  
  tags:
    - lab
